#!/usr/bin/env bash
#MISE description="Run GitHub Actions lint suite"
#MISE tools={"aqua:koalaman/shellcheck"="0.11.0","aqua:rhysd/actionlint"="1.7.12","aqua:suzuki-shunsuke/ghalint"="1.5.6","aqua:suzuki-shunsuke/pinact"="3.9.2","aqua:zizmorcore/zizmor"="1.24.1"}
set -e

cd "$MISE_PROJECT_ROOT"

pinact run
zizmor --fix --pedantic .github/workflows/
actionlint
ghalint run
