#!/usr/bin/env bash
#MISE description="Run GitHub Actions lint suite"
#MISE tools={"aqua:koalaman/shellcheck"="0.11.0","aqua:rhysd/actionlint"="1.7.12","aqua:suzuki-shunsuke/ghalint"="1.5.6","aqua:suzuki-shunsuke/pinact"="4.1.0","aqua:zizmorcore/zizmor"="1.25.2"}
set -e

cd "$MISE_PROJECT_ROOT"

pinact run --verify
zizmor --fix --pedantic .github/workflows/
actionlint
ghalint run
