#!/usr/bin/env bash
#MISE description="Prune unused entries from tracked .gitignore files"
#MISE tools={"github:iwamot/gitignore-prune"="0.1.1"}
set -e

cd "$MISE_PROJECT_ROOT"

gitignore-prune --fix
