name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: iwamot/workflows/.github/workflows/ci.yml@3926091bedbf975210db444221da3bc5e3620492 # v0.7.1
