name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: iwamot/workflows/.github/workflows/dependabot-auto-merge.yml@3d98819f349a88597f2d2c7b171a973c2aea5aa1 # v0.3.0
