name: 'Dependency review'
on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    uses: iwamot/workflows/.github/workflows/dependency-review.yml@b0698502d33114e71eb6b4a242b337fdec60d430 # v0.2.0
