name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: iwamot/workflows/.github/workflows/dependabot-auto-merge.yml@b0698502d33114e71eb6b4a242b337fdec60d430 # v0.2.0
